### REGISTERS USERS
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "tes user",
  "password": "1234",
  "phoneNumber": "081234567890",
  "name": "Test Almanac"
}

### REGISTERS PROVIDERS
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "tes provider 39",
  "password": "1234",
  "phoneNumber": "081234567839",
  "name": "Test Almanac",
  "role": "provider"
}

### REGISTERS ADMIN
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "tes admin",
  "password": "1234",
  "phoneNumber": "081234567892",
  "name": "Test Almanac",
  "role": "admin"
}

### LOGIN USERS
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test admin",
  "password": "1234",
  "phoneNumber": "081335594715",
  "name": "Test Almanac"
}

### GET PROFILE
GET http://localhost:3000/api/auth/me/clhlogokm0004vj2c5wqwo9fz
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsaGxsMnQ5aTAwMDB2ajAwY2QyaXJ4ejUiLCJlbWFpbCI6InRlc3QiLCJpYXQiOjE2ODM5Njg5ODksImV4cCI6MTY4NDA1NTM4OX0.8lW-bVrt0WXeqxCAZEhjAPw2nj1Ny7t8pcdrJRbOzwM