### REGISTERS USERS
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "tes user",
  "password": "1234",
  "phoneNumber": "081234567890",
  "name": "Test Almanac"
}

### REGISTERS PROVIDERS
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "tes provider 39",
  "password": "1234",
  "phoneNumber": "081234567839",
  "name": "Test Almanac",
  "role": "provider"
}

### REGISTERS ADMIN
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "tes admin",
  "password": "1234",
  "phoneNumber": "081234567892",
  "name": "Test Almanac",
  "role": "admin"
}

### LOGIN USERS
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "tes provider",
  "password": "1234",
  "name": "Test Almanac"
}

### GET PROFILE
GET http://localhost:3000/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsaG00YXdrcjAwMDF2anFzOW1yMDV2dWYiLCJlbWFpbCI6InRlcyBwcm92aWRlciIsImlhdCI6MTY4NDAxNDc5NSwiZXhwIjoxNjg0MTAxMTk1fQ.s2UYnfPYMexS5ZcuhNqMyw92WQGKYGBEL9EvAVWgf1A