### GET ALL CATEGORY PRODUCT
GET http://localhost:3000/api/category-product

### CREATE CATEGORY PRODUCT
POST http://localhost:3000/api/category-product
Content-Type:  application/json

{
  "name": "Test 1"
}