### GET SERVICE
GET http://localhost:3000/api/provider-service

### CREATE SERVICE
POST http://localhost:3000/api/provider-service
Content-Type: application/json

{
  "namaUsaha": "Kunci sehat",
  "priceMax": 10000,
  "priceMin": 10000,
  "service": "test",
  "userId": "clhm6rij10006vhnlgczbd7ib",
  "categoryProductId" : "clhm7bibz0000vhjqr2mmqu9s"
}