### CREATE SERVICE
POST http://localhost:3000/api/provider-service
Content-Type: application/json

{
  "namaUsaha": "fitra",
  "priceMax": 100000,
  "priceMin": 1000,
  "service": "test",
  "userId": "clhm21xr10000vhtyvzekrgzl",
  "categoryProductId" : "clhm7bibz0000vhjqr2mmqu9s"
}