### GET SERVICE
GET http://localhost:3001/api/provider-service

### GET SERVICE BY ID
GET http://localhost:3001/api/provider-service/clhm8vnla0001vhmqbrs77jli

### CREATE SERVICE
POST http://localhost:3001/api/provider-service
Content-Type: application/json

{
  "namaUsaha": "Kunci sehat",
  "priceMax": 10000,
  "priceMin": 10000,
  "service": "test",
  "userId": "clhmo28ex000bvhcdsg67mw03",
  "categoryProductId" : "clhmo18uc0000vhcdjca6j3in"
}